title: "Masaya Honda"
author: "Masaya Honda"
description: " "
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
mathjax: true

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true              # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  # - {file: "about.md", icon: address-card, title: "Masaya Honda"}
  - {file: "about.md", title: "About me"}
  - {file: "projects.md", icon: microchip, title: "Projects"}
  - {file: "resume.pdf", icon: file , title: "CV"}
  
external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/masaya-honda-5b206b167"}
  - {title: Mail, icon: envelope, url: "mailto:jp.masaya@gmail.com"}
  - {title: Github, icon: github, uril: "https://github.com/mahonda"}
  

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
